add fedora support
nephio-project/test-infra pull request #120
Opened 2023-06-22 09:19 UTC by vjayaramrh

This PR adds support for Fedora34 that has the kernel version of 5.17.6. Was able to execute the steps at https://github.com/nephio-project/test-infra/blob/main/e2e/provision/README.md successfully.

Note:
-  Fedora versions above 34 have kernel version greater than 6.0.0 which does not support building and installing gtp5g kernel modules.
-  PR was tested on a Fedora VM running on baremetal
- Fedora 34 VM on gcp cloud does not allow ssh login and hence was unable to test out in gcp fedora34 VM.

2023-06-22 09:28 UTC, liamfallon commented
/approve

2023-06-22 09:53 UTC, gvbalaji approved these changes
Thanks @vjayaramrh . Added a comment but overall looks good.

2023-06-22 09:53 UTC, gvbalaji commented on e2e/provision/playbooks/roles/bootstrap/vars/redhat.yml
What's this file for?  If this is needed can we rename the file to a  more neutral name?

2023-06-22 15:40 UTC, electrocucaracha reviewed
Hi @vjayaramrh, I besides the suggestions that I let can you include a change into the [platforms section of the molecule file](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml#L24-L31)?. I suggest using a [generic](https://app.vagrantup.com/generic) Vagrant box, given they have support for VirtualBox and Libvirt providers.

2023-06-22 15:40 UTC, electrocucaracha commented on e2e/provision/install_sandbox.sh
> +
Same thing here
```suggestion
    # shellcheck disable=SC1091
    source /etc/os-release || source /usr/lib/os-release
    case ${ID,,} in
    ubuntu | debian)
        sudo apt-get update
        sudo -E DEBIAN_FRONTEND=noninteractive apt-get remove -q -y python3-openssl
        sudo -E NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --allow-downgrades --allow-remove-essential --allow-change-held-packages -fuy install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" python3-pip
        ;;
    rhel | centos | fedora | rocky)
        PKG_MANAGER=$(command -v dnf || command -v yum)
        sudo $PKG_MANAGER install python3-pip -y
        ;;
    *)
        echo "OS not supported"
        exit
        ;;
    esac

```

2023-06-22 19:13 UTC, electrocucaracha commented
> Hi @vjayaramrh, I besides the suggestions that I let can you include a change into the [platforms section of the molecule file](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml#L24-L31)?. I suggest using a [generic](https://app.vagrantup.com/generic) Vagrant box, given they have support for VirtualBox and Libvirt providers.

I almost forgot, can you also update the [workflow diagram](https://github.com/nephio-project/test-infra/tree/main/e2e/provision/playbooks/roles/bootstrap#workflow)?

2023-06-23 06:12 UTC, radoslawc commented on e2e/provision/init.sh
> +    fi
👍

2023-06-23 06:12 UTC, radoslawc commented on e2e/provision/install_sandbox.sh
> +
👍

2023-06-23 06:15 UTC, radoslawc commented
I like Victor's suggestions for OS detection otherwise /lgtm

2023-06-23 07:15 UTC, radoslawc commented
/approve

2023-06-23 08:58 UTC, vjayaramrh commented on e2e/provision/init.sh
> +    fi
@electrocucaracha trying to understand what's lacking in the existing check? I find it more readable. What does source do and how is $ID getting populated, it seems cryptic to me.

2023-06-23 12:24 UTC, vjayaramrh commented on e2e/provision/init.sh
> +    fi
I think I get it now

2023-06-23 15:24 UTC, electrocucaracha commented on e2e/provision/init.sh
> +    fi
Using a switch/case can make it more readable and enable future additions like openSUSE

2023-06-23 15:37 UTC, electrocucaracha requested changes
@vjayaramrh could you include a platform to validate it with `tox -e bootstrap`?

2023-06-23 15:37 UTC, electrocucaracha commented on e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
> +
```suggestion
```

2023-06-26 00:50 UTC, vjayaramrh commented on e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
> +  when: ansible_os_family == 'Debian'
Great suggestion

2023-06-26 09:54 UTC, vjayaramrh commented on e2e/provision/playbooks/roles/bootstrap/vars/redhat.yml
> +  - make
Suggestion implemented

2023-06-26 09:55 UTC, vjayaramrh commented
> Hi @vjayaramrh, I besides the suggestions that I let can you include a change into the [platforms section of the molecule file](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml#L24-L31)?. I suggest using a [generic](https://app.vagrantup.com/generic) Vagrant box, given they have support for VirtualBox and Libvirt providers.

FYI Suggestion related to VirtualBox and Libvirt providers for Fedora34 implemented

2023-06-26 12:23 UTC, vjayaramrh commented
@electrocucaracha Have addressed your comments and suggestions. Would appreciate your review and lgtm
cc: @radoslawc

2023-06-26 23:19 UTC, electrocucaracha reviewed
@vjayaramrh I was running `tox -a bootstrap` and it seems like the [`Update Apt cache`](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml#L14-L17) task needs to be changed to include an OS conditional.

2023-06-26 23:19 UTC, electrocucaracha commented on e2e/provision/playbooks/roles/bootstrap/README.md
>      E --> F(Install compilation packages)
```suggestion
    E --> F(nstall compilation packages and kernel development tools on Debian/RedHat)
```

2023-06-27 00:14 UTC, vjayaramrh commented
> @vjayaramrh I was running `tox -a bootstrap` and it seems like the [`Update Apt cache`](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml#L14-L17) task needs to be changed to include an OS conditional.

Done

2023-06-27 01:06 UTC, electrocucaracha commented
/lgtm

2023-06-27 03:01 UTC, electrocucaracha commented
/lgtm

2023-06-27 09:05 UTC, radoslawc commented
/approve
/lgtm
/override e2e

2023-06-27 09:05 UTC, merged