Add docker registry mirror support
nephio-project/test-infra pull request #184
Opened 2023-09-11 14:57 UTC by kispaljr

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
It enables the ansible playbook to set docker registry mirrors for the docker engine in the sandbox VM and also for the management kind cluster deployed by the playbook. The list of registry mirrors is expected to be in the DOCKER_REGISTRY_MIRRORS environment variable in JSON format.

We need this, because in some company intranets DockerHub access has to go through a company-wide docker registry mirror by company policy.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Enable setting docker registry mirrors in the sandbox environment.
```

2023-09-11 14:58 UTC, kispaljr commented
/kind bug

2023-09-11 15:48 UTC, radoslawc commented
/ok-to-test

2023-09-11 16:59 UTC, radoslawc commented
/approve

2023-09-11 20:18 UTC, electrocucaracha commented on e2e/provision/playbooks/cluster.yml
> +
@kispaljr correct me if I'm wrong, but it seems like `registry-mirrors` and `docker_engine_daemon_json` vars are not used anywhere. Do we need to set those facts?

2023-09-11 20:22 UTC, electrocucaracha commented on e2e/provision/playbooks/cluster.yml
> +
Nevermind, I just noticed that is for the [`docker_engine` role](https://github.com/andrewrothstein/ansible-docker_engine/blob/v0.2.2/tasks/main.yml#L34-L50)

2023-09-11 20:30 UTC, electrocucaracha requested changes
@kispaljr I've suggested removing some trailing spaces to avoid issues to the Ansible linter, other than that it looks good to be merged. Don't forget to modify the installation guide to include the env var, you can take a look of this similar change https://github.com/nephio-project/docs/pull/62

2023-09-11 20:30 UTC, electrocucaracha commented on e2e/provision/playbooks/cluster.yml
> +            docker_engine_daemon_json:
```suggestion
            docker_engine_daemon_json:
```

2023-09-11 20:30 UTC, electrocucaracha commented on e2e/provision/playbooks/roles/bootstrap/tasks/create-mgmt.yml
> +            endpoint = {{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_MIRRORS') | from_json }}
```suggestion
            endpoint = {{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_MIRRORS') | from_json }}
```

2023-09-12 13:08 UTC, kispaljr commented on e2e/provision/playbooks/cluster.yml
> +            docker_engine_daemon_json:
Fixed in da4bcb3

2023-09-12 13:08 UTC, kispaljr commented on e2e/provision/playbooks/roles/bootstrap/tasks/create-mgmt.yml
> +            endpoint = {{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_MIRRORS') | from_json }}
Fixed in da4bcb3

2023-09-12 13:53 UTC, kispaljr commented
I fixed the linter errors. and I am still trying to interpret the output of the failed tests.

2023-09-12 17:02 UTC, electrocucaracha commented
> I fixed the linter errors. and I am still trying to interpret the output of the failed tests.

We have seen some inconsistent issues to bringing up the uesimtun0 nic which is [causing ](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_test-infra/184/e2e-ubuntu-focal/1701598024968441856#1:build-log.txt%3A68650) timeouts. This issue is not related with the change you're submitting.

/lgtm

/override e2e-ubuntu-focal

2023-09-12 17:02 UTC, merged