Adding OAI RAN and UE test deployment scripts
nephio-project/test-infra pull request #227
Opened 2023-12-18 18:01 UTC by josephthaliath

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-12-18 18:05 UTC, johnbelamaric commented
/ok-to-test

I also fixed it so that won't be needed anymore (gave the sig-automation team Triage access on this repo)

2023-12-18 18:22 UTC, electrocucaracha requested changes
@josephthaliath I made few suggestions on these files, don't forget to add information into the description of the PR

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/002.sh
> +kpt alpha repo register --namespace default https://github.com/josephthaliath/catalog.git --directory=workloads/oai --name=oai-ran-packages
@josephthaliath are you using this [PR](https://github.com/nephio-project/catalog/pull/11) for these tests?

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/002-oai-operators.yaml
> +        approval.nephio.org/policy: initial
It seems like you have a line ending at in the file, maybe it's added by your text editor

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/002-oai-operators.yaml
> +    revision: v1
Are you sure that this is the right revision?
```suggestion
    revision: r2
```

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/002.sh
> +k8s_wait_ready_replicas "deployment" "oai-ran-operator" "$(k8s_get_capi_kubeconfig "edge")" "oai-ran-operators"
Maybe we can store the value of kubeconfig of the edge and reuse it.
```suggestion
_edge_kubeconfig="$(k8s_get_capi_kubeconfig "edge")"
k8s_wait_ready_replicas "deployment" "oai-upf-controller" "$_edge_kubeconfig" "oai-operators"
k8s_wait_ready_replicas "deployment" "oai-ran-operator" "$(k8s_get_capi_kubeconfig "regional")" "oai-ran-operators"
k8s_wait_ready_replicas "deployment" "oai-ran-operator" "$_edge_kubeconfig" "oai-ran-operators"
```

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/004.sh
> +EOF
I think that we can create a separate file for this.

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/004.sh
> +source "${LIBDIR}/_assertions.sh"
I don't think that the functions stored in these files are being used

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/005.sh
> +source "${LIBDIR}/_assertions.sh"
Same thing here, I don't think those are being used

2023-12-18 18:22 UTC, electrocucaracha commented on e2e/tests/oai/005.sh
> +EOF
We can keep this code in a separate yaml file

2024-01-02 16:43 UTC, radoslawc commented
/approve

2024-01-04 16:59 UTC, electrocucaracha commented
@josephthaliath could you fill some information in the PR's description? I'll be reviewing the errors

2024-01-05 00:18 UTC, josephthaliath commented
> @josephthaliath could you fill some information in the PR's description? I'll be reviewing the errors

@electrocucaracha , I have updated PR description

2024-01-15 14:38 UTC, radoslawc commented
/test e2e-free5gc-ubuntu-focal
/test e2e-oai-ubuntu-jammy

2024-01-16 19:59 UTC, electrocucaracha requested changes
These suggestions require merging the https://github.com/nephio-project/test-infra/pull/230

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/002-oai-operators.yaml
> +    package: workloads/oai/oai-ran-operator
```suggestion
    repo: catalog-workloads-oai-ran
    package: oai-ran-operator
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/004-ran-cucp.yaml
> +    package: workloads/oai/pkg-example-cucp-bp
```suggestion
    repo: catalog-workloads-oai-ran
    package: pkg-example-cucp-bp
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/004-ran-cucp.yaml
> +# Copyright (c) 2023 The Nephio Authors.
```suggestion
# Copyright (c) 2024 The Nephio Authors.
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/004.sh
> +# Copyright (c) 2023 The Nephio Authors.
```suggestion
# Copyright (c) 2024 The Nephio Authors.
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/004.sh
> +    package: workloads/oai/pkg-example-$nf-bp
```suggestion
    repo: catalog-workloads-oai-ran
    package: pkg-example-$nf-bp
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/005.sh
> +# Copyright (c) 2023 The Nephio Authors.
```suggestion
# Copyright (c) 2024 The Nephio Authors.
```

2024-01-16 19:59 UTC, electrocucaracha commented on e2e/tests/oai/005.sh
> +    package: workloads/oai/pkg-example-ue-bp
```suggestion
    repo: catalog-workloads-oai-ran
    package: pkg-example-ue-bp
```

2024-01-17 17:40 UTC, electrocucaracha commented
@josephthaliath did you rebase this PR with the latest changes?

2024-01-17 21:20 UTC, electrocucaracha commented
It seems like the tests are passing the 75 min threshold, so we will need [this change](https://github.com/nephio-project/test-infra/pull/230/commits/b27db45fb50e4a28d0d86f7b9e2998c517304b22) to increase the timeout

2024-01-17 22:28 UTC, arora-sagar commented
@josephthaliath Can you avoid deploying RAN operator on the core cluster if possible?

2024-01-17 22:36 UTC, arora-sagar commented
@josephthaliath @electrocucaracha I merged this with main branch and everything went well. The end to end test was working fine. Here you can see some numbers. 

```
./init.sh --> 12 mins
001.sh --> 20:49:23 -- 21:06:04 --> 15 mins
002.sh --> 21:06:58 -- 21:09:59 --> 3 mins
003.sh --> 21:11:37 -- 21:42:26 --> 31 mins 
004.sh --> 22:00:46 -- 22:24:15 --> 24 mins
005.sh --> 22:26:10 -- 22:27:43 --> 1 min
```

I think the timeout for end to end test should be 100 or 120 mins to be on the safe side. We can reduce it if we see it takes less time.

2024-01-18 16:26 UTC, arora-sagar commented on test-infra_18jan_v1.diff
@josephthaliath I don't think this file is needed

2024-01-19 00:55 UTC, josephthaliath commented on test-infra_18jan_v1.diff
@arora-sagar . Thanks. added by mistake. removed it.

2024-01-22 20:54 UTC, electrocucaracha commented
/lgtm
/approve

2024-01-22 21:11 UTC, electrocucaracha commented
/override e2e-free5gc-fedora-34
/override e2e-free5gc-ubuntu-focal
/override e2e-oai-ubuntu-jammy

2024-01-22 21:12 UTC, merged