add support for installing nonKIND cluster via kubeadm
nephio-project/test-infra pull request #46
Opened 2023-05-23 03:29 UTC by vjayaramrh

allows for installing nonKIND K8S cluster on ubuntu and fedora for e2e test cases

2023-05-25 07:32 UTC, radoslawc reviewed
/approve

2023-05-25 07:32 UTC, radoslawc commented on e2e/provision/vars/kubeadm.yaml
> +containerd_ver: 1.6.19
I like that those are in vars file, gj

2023-05-31 14:32 UTC, vjayaramrh commented
> There are several things to consider for this approach:
> 
>     * Maintenance: There are [plenty of mature options](https://www.cncf.io/certification/software-conformance/) to deploy production-ready Kubernetes clusters. [Kubespray](https://kubespray.io/#/) has been used by several projects, but we can make a deep analysis on others.
> 
>     * Cluster API support: Using non-KinD cluster will result in a different [Infrastructure Cluster API provider](https://cluster-api.sigs.k8s.io/reference/providers.html).

@electrocucaracha Great points, This is now a first step and we should definitely iterate to get there.

2023-06-13 16:13 UTC, radoslawc commented
/lgtm

2023-06-13 16:15 UTC, electrocucaracha commented
/hold

2024-08-07 15:32 UTC, dkosteck requested changes
Changes noted per testing on Fedora 34, including the change to the Kubernetes repo source and versioning. Either the k8s_ver flag should be removed as suggested, or a higher version that is supported on Fedora should be used for this flag

2024-08-07 15:32 UTC, dkosteck commented on e2e/provision/roles/deploy_kubeadm_k8s/tasks/kubeadm-RedHat.yaml
> +        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```suggestion
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
```

2024-08-07 15:32 UTC, dkosteck commented on e2e/provision/roles/deploy_kubeadm_k8s/tasks/kubeadm-RedHat.yaml
> +          - kubectl <= {{ k8s_ver }}
```suggestion
          - kubelet
          - kubeadm
          - kubectl
```

2024-08-07 20:19 UTC, dkosteck requested changes

2024-08-07 20:19 UTC, dkosteck commented on e2e/provision/vars/kubeadm.yaml
> +k8s_ver: 1.25
```suggestion
k8s_ver: 1.30
```

2024-08-15 20:13 UTC, closed without merging